### ISSUE TITLE
Right usage of Key-Value pair for the `InfoS` / `ErrorS`

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/logtools#7]
I stumbled into an issue because of a mistake that I might have done in the code while opening a PR against a k/k repo. 

While invoking the `klog.InfoS` and `klog.ErrorS`, in order to avoid having to add the key-value pairs in each of the invocations, I was creating them into an array of `interface{}` types and passing them as argument to the `klog.InfoS` and `klog.ErrorS` and looks like the checks we have do not like that way of passing the data around. 

```golang
kvPairs := []interface{}{"some-key", "some-value", "other-key": "other-value"}
klog.InfoS("Some message", kvPairs...)
```

The above was the format I was using to generate the logs which renders a series of failures while linting

```bash
pkg/kubelet/logs/container_log_manager.go:286:3: Additional arguments to ErrorS should always be Key Value pairs. Please check if there is any key or value missing. (logcheck)
		klog.ErrorS(err, "Failed to get container status", attrs...)
		^
pkg/kubelet/logs/container_log_manager.go:290:3: Additional arguments to ErrorS should always be Key Value pairs. Please check if there is any key or value missing. (logcheck)
		klog.ErrorS(err, "Container status is nil", attrs...)
		^
pkg/kubelet/logs/container_log_manager.go:298:4: Additional arguments to ErrorS should always be Key Value pairs. Please check if there is any key or value missing. (logcheck)
			klog.ErrorS(err, "Failed to stat container log", attrs...)
			^
pkg/kubelet/logs/container_log_manager.go:303:4: Additional arguments to ErrorS should always be Key Value pairs. Please check if there is any key or value missing. (logcheck)
			klog.ErrorS(err, "Container log doesn't exist, reopen container log failed", attrs...)
			^
```

xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114301/pull-kubernetes-verify/1600026050757136384

With that said, this is more of a question than a bug report. Is what I am doing the right thing? If so, should we fix the linter to allow this format of extending and including the key-value pairs for the logger ?

**Comment by pohly** [comment]
I ran into this myself before. The logcheck tool is too limited to check the parameters when they come from a slice and therefore apparently a deliberate decision was made to warn about such invocations.

In Kubernetes, you can use `// nolint:logcheck` for specific invocations where ignoring that limitation makes sense:

https://github.com/kubernetes/kubernetes/blob/17bf864c1fc20e4badc9a6e0659c5190310462e1/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go#L52-L53

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/json/json_test.go#L84-L85

You said "in order to avoid having to add the key-value pairs in each of the invocations" - this sounds like a use case for `WithValues`. The problem being of course that we cannot rely on that yet. So without having looked at your code it sounds like a `[]interface{}` with a comment about future usage of `WithValues` may be appropriate, followed by nolint suppressions.

**Comment by harshanarayana** [comment]
@pohly  Thanks very much for the quick feedback. For now I switched to using the kv-pairs directly inline with the logs. But I should have checked the other usage of `// nolint: logcheck` you referenced. I will keep that in mind the next time I have to do something like this.

**Comment by harshanarayana** [comment]
>  this sounds like a use case for WithValues. The problem being of course that we cannot rely on that yet

Yup. This would be wonderful to have in the `klog.{Info|Error}S`. Do you already have this in your backlog to get a working version going or should I create a tracker in the klog repo. I can help with the implementation if required.

**Comment by pohly** [comment]
Oh, this isn't even about contextual logging. No, let's not add further features to klog. Everybody should switch over to contextual logging where `WithValues` is already supported (if enabled...).
